### ISSUE TITLE
Network queries crash on ToString()

### ISSUE THREAD

**Issue by edwellbrook** [SamuelCox/Noise#7]
Network queries such as 

```
SERVER_CONNECT
SERVER_DISCONNECT
SERVER_START
SERVER_STOP
```

exist as only a command, and will crash when ToString is called. This is from a null pointer exception from not having a `Key` or `Argument`.

**Comment by SamuelCox** [comment]
Hey, yeah I'm aware of this. It's trivial to fix, but I'm waiting until the conversion to C# 6.0 #4  because of the null conditional operator. ToString will become Query?.Command?.ToString(), Argument?.ToString() etc. This is way cleaner than doing a few if statements or ternary operators so I'm waiting on that, until then you just have to make sure to delimit them with commas, inserting empty keys and arguments, such as server_connect,,
